# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"

    # Note that the session will be started ONLY if you read or write from it.
    session:
        enabled: true

        #Session Cookie
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax
        name: KNOWLEDGESESSID
    csrf_protection:
        stateless_token_ids: ["auth", "api"]

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
