security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\User: "auto"

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        api:
            pattern: ^/api
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            stateless: false
            context: api
            # Connection via JSON (session cookie)
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password

            logout:
                path: /api/auth/logout

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        # Public endpoints
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/verify-email, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/csrf, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/themes, roles: PUBLIC_ACCESS }
        - { path: ^/api/cursus, roles: PUBLIC_ACCESS }
        - { path: ^/api/stripe/webhook, roles: PUBLIC_ACCESS }

        # Logout accessible if logged in
        - { path: ^/api/auth/logout, roles: IS_AUTHENTICATED_FULLY }

        # Back-office endpoints (admin only)
        - { path: ^/api/admin, roles: ROLE_ADMIN }

        # The rest of the API requires authentication
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            App\Entity\User:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
